name: ci/cd pipeline to deploy to tomcat
on:
   push:
      branches: main
jobs:
   build-deploy:
     runs-on: ubuntu-latest
     steps:
       - name: checkout code
         uses: actions/checkout@v5
       - name: set-up jdk
         uses: actions/setup-java@v5
         with:
           distribution: 'temurin'
           java-version: '17'
           
       - name: validate with maven  
         run: mvn validate
       - name: compile with maven  
         run: mvn compile 
       - name: test with maven  
         run: mvn test
       - name: package with maven  
         run: mvn package
       - name: verify war file  
         run: ls -lh target/
       - name: Deploy to Tomcat
         run: |
          curl -u "${{ secrets.TOMCAT_USER }}:${{ secrets.TOMCAT_PASSWORD }}" \
          -T target/TrainBook-1.0.0-SNAPSHOT.war \
          "${{ secrets.TOMCAT_URL }}/manager/text/deploy?path=/TrainBook&update=true"
       
